### ISSUE TITLE
Mostrando apenas a hora

### ISSUE THREAD

**Issue by Emerson-MM-Filho** [lucaassos/Hora-do-dia-#1]
It shows only the hours (without minutes) because you are just taking the hour.

https://github.com/lucaassos/Hora-do-dia-/blob/fb713146fe75c37ab3c1e254fe694bd7110fa31f/script001.js#L5

You need to extract the minutes on the date object and concatenate them on the template string as you did with the hour.
https://github.com/lucaassos/Hora-do-dia-/blob/fb713146fe75c37ab3c1e254fe694bd7110fa31f/script001.js#L6

**Comment by lucaassos** [comment]
I concatenated the minutes with the hours and added colors to change according to the season of the day
